added Search Bar and search function to interpret search query
cu-flow/cu-flow pull request #7
Opened 2023-05-06 04:44 UTC by Blandon22

## Changes Made
Added Search Bar and search Function
### Screenshots
![image](https://user-images.githubusercontent.com/91898887/236600251-5166e753-fd54-4ef8-ba1f-ef21bf243f19.png)
![image](https://user-images.githubusercontent.com/91898887/236600256-9ee49fef-40d3-4706-a0de-571f56c3e019.png)

## Future Steps
Finalize search bar sizing across all screen sizes. Currently, it's using arbitrary proportions for small, medium, and large screens. 
## Checklist

- [] Functionality works and does not implicate other code
- [] Written tests if applicable
- [] Error checking if applicable
- [] Code quality 

#### Issues Resolved

Closes #

2023-05-06 05:18 UTC, kunwar45 requested changes
Amazing! Just change the file name from `SearchBar.js` to `SearchBar.jsx`. jsx works better for react

2023-05-06 05:18 UTC, kunwar45 commented on carleton-pathways/src/components/searchBar/SearchBar.js
> +
Add a empty react tag of `<>` here.

2023-05-06 05:18 UTC, kunwar45 commented on carleton-pathways/src/components/searchBar/SearchBar.js
> +</div>
add a closing react tag of `</>` here

2023-05-15 23:45 UTC, Iman1121 approved these changes
Nice work!

2023-05-15 23:46 UTC, kunwar45 approved these changes

2023-05-15 23:48 UTC, merged